### PR TITLE
Init go project with pipeline.

### PR DESCRIPTION
**Pull request by rgaiffe**
Initialisation of go project packaged at "github.com/42Stellar/webhooks"
Create pipeline github Actions for test unit only, need to work on build.

Create Dockerfile and build.sh file.

### CODE REVIEW

**Comment by 42Atomys** [comment]
Good, maybe pass to `42stellar.org/webhooks` instead of github.com url. Just for flex

**Comment by rgaiffe** [comment]
Done , the package name is 42Stellar.org/webhooks

**Comment by 42Atomys** [comment]
I prepare the go-proxy, maybe I will create a simple go app to automate this simple work. 

Repository : https://github.com/42Atomys/simple-go-proxy

**Comment by 42Atomys** [comment]
I am doing the redirection manually for the moment

**Review by 42Atomys — APPROVED** [review]
LGTM 🎉

**Pull request merged**
